Bill-Gray/PDCursesMod

win32a/pdcscrn.c
This fixes compilation failing on GCC 5.3.0 on MSYS2 when compiling with DEBUG defined.
The errors I received were as follows:
```
gcc -g -Wall -DPDCDEBUG -I.. -mwindows -otestcurs.exe ../demos/testcurs.c pdcurses.a -lgdi32 -lcomdlg32
pdcurses.a(pdcscrn.o): In function `final_cleanup':
..\PDCurses\win32a/../win32a/pdcscrn.c:109: undefined reference to `set_default_sizes_from_registry'
pdcurses.a(pdcscrn.o): In function `rectangle_from_chars_to_pixels':
...\PDCurses\win32a/../win32a/pdcscrn.c:779: undefined reference to `sort_out_rect'
pdcurses.a(pdcscrn.o): In function `WndProc':
...\PDCurses\win32a/../win32a/pdcscrn.c:1793: undefined reference to `HandleSizing'
...\PDCurses\win32a/../win32a/pdcscrn.c:1839: undefined reference to `HandleBlockCopy' …
```
=> Changed INLINE definition from inline to static inline in pdcscrn.c

.gitignore, win32a/pdcscrn.c
Link to original pull request: https://github.com/Bill-Gray/PDCurses/pull/8
- Added auto-screen repositioning for multi-monitors based on an
MSDN example (links in source code).
- Added .gitignore to ignore compile artifacts.
=> Win32a multi-monitor support, take 2.

win32a/pdcscrn.c
Before this patch, the "Menu" item will always be checked at the start of the program even if the menu is not being shown based on the settings in the registry.
=> Correctly initialize the checked state of the "Menu" system menu item.

exp-base.def, term.h
These should not be part of the def files as they are `external`ized already:
* exp-base.def: comment the `PDCEX` entries out
* term.h: use `PDCEX` define from curses.h
=> Cleanup for `PDCEX` entries

dos/gccdos.mak, dos/pdcutil.c
As my time machine doesn't work I've setup FreeDOS which includes DJGPP GCC 4.7 where I wanted to *use* a nice piece of software that needs to run configure (or a lot of hand work) to be build and has non 8.3 files that aren't easily to transfer/compile in FreeDOS.
Therefore I've created an i586-pc-msdosdjgpp cross compilation environment on my Trisquel box and tried to use gccdos.mak (after manually setting activating the i586-pc-msdosdjgpp environment) to compile PDCurses. And it mostly worked.
The minimal needed changes are part of the current PR, if there's any interest in this I'll add the  `i586-pc-msdosdjgpp-` prefix for the tools and try to do a fresh compile without any manual setup.
@Bill-Gray: What do you think?
BTW: As the ftpserver refuses to work in my FreeDOS environment …
=> Allow cross-compile for dos from GNU/Linux

HISTORY.md, curspriv.h, dos/pdcutil.c, dos/wccdos16.mak, watcom.mif
Here is a proposed patch to `dos/pdcutil.c` which fixes `PDC_napms(.)` to correctly handle a few corner cases, namely
* where an extremely long sleep length is requested (possible with 32-bit DOS extenders);
* where a sleep request crosses midnight;
* where, between reading the two shortwords in the timer tick count (`0:0x46c`), a timer interrupt occurs.
In addition, I have (hopefully) improved the accuracy of converting from milliseconds to ticks.
While I was at it, I also modified `dos/wccdos16.mak` and `watcom.mif`, so that they can now work with Open Watcom C/C++ 2.0 to cross-compile DOS code from Linux.
Thank you!
=> Patch to fix corner cases in PDC_napms(.) for DOS, and allow cross-compiling with Open Watcom

demos/testcurs.c
Note: `PDC_set_resize_limits` and `PDC_set_function_key` may get a better define to check than "major version defined".
Other demos would likely need similar tweaks.
=> Update testcurs.c to compile with PDCurses 3.4-3.6

win32a/pdcscrn.c
This fixes the buffer overflow in `get_app_name()` when a PDCurses executable is started with very long commandline arguments (issue #80).
=> get_app_name() buffer overflow fix

demos/testcurs.c, ncurses/makefile
1.  Fixes testcurs.c warning:
```
../demos/testcurs.c: In function ‘scrollTest’:
../demos/testcurs.c:371:9: warning: variable ‘OldX’ set but not used [-Wunused-but-set-variable]
int OldX;
^
```
2.  Fixes ncurses makefile, so that it properly links ncurses lib per WIDE=Y/N choice.
=> compiler warning fix, lib linkage correctness

wincon/pdckbd.c
This is a follow-up to 7eb27ea which brought the code from wmcbrine's to
support user resizing of Windows console. Since that time,
https://github.com/wmcbrine/PDCurses/issues/30 was reported and fixed in
wmcbrine's 9cf39fe. This commit mirrors that fix.
While I have your attention.. do you have plans to make a new release anytime soon? I was looking to get resizing working in https://github.com/MitMaro/git-interactive-rebase-tool which relies on https://github.com/ihalila/pdcurses-sys , which makes your code available as a neat Rust crate(package). I feel I should wait for a proper release on your side before asking for the Rust crate to be updated.
=> KEY_RESIZE should be key_code = TRUE in wincon

demos/tui.c
Added:Mouse handling to tuidemo regarding menus,sub-menus&dialogs
as per request in https://github.com/Bill-Gray/PDCurses/issues/35
This patch include, open a menu ,close a menu and paste text from the mouse clipboard to the sub-fields of the tuidemo.
Notes;
1) The mouse clipboard will work only by activating insert mode [KEY_IC/KEY_EIC] on the keyboard and by using the right click button of the mouse to paste one string of text.
2) Clicking or double clicking outside the current opened menu will be considered as [KEY_ESC].
3) One click to highlight the chosen menu.
4) Double clicking on the highlighted menu to open it.
=> Added:Mouse handling to tuidemo

curses.h
`__STDC_VERSION` is not a standard macro but `__STDC_VERSION__` is.
=> Correct use of __STDC_VERSION__

wincon/pdckbd.c
Previously PDCurses would send (X,Y) coordinates (-1,-1) when processing a scroll event. Bring the behavior inline with ncurses and send the actual mouse position.
Reference https://github.com/wmcbrine/PDCurses/issues/88.
=> WINCON: Send real mouse position with scroll event

cmake/version.in.cmake
When running a dll build using MSVC and CMake, I am getting the error RC2135 for the file cmake/version.in. It appears to be related to a missing icon reference.
I believe that after removing the project icon in 4ee573a73c8dfaa10d7934b4239824a9c772e7e6 we need to remove the reference to it in the resource file as well. This patch fixes the issue for me.
=> Removed reference to icon from cmake/version.in.cmake

appveyor.yml, cmake/watcom_open_dos16_toolchain.cmake, cmake/watcom_open_dos32_toolchain.cmake, cmake/watcom_open_os2v2_toolchain.cmake
overwrite CMake default values, they are only valid for Windows, not for cross-compilation
correct compiler driver name for 16-bit
=> correct OW cross-compilation CMake scripts

wingui/pdcscrn.c
With current PDCurses, if there is an existing registry entry for a WinGUI program under HKEY_CURRENT_USER\Software\PDCurses, the resize limits contained therein will override those set programmatically by a call to PDC_set_resize_limits() before initscr().
For example, let's say you built and ran a WinGUI program without support for resizing, then rebuilt the program with support, using a call to PDC_set_resize_limits(). The window will still not be resizable, because the old limits leftover in the registry will override your call.
One could use ttytype[0...3] instead to set the resize limits, as documented, to avoid this problem (because WinGUI's initscr() reads these values after calling get_default_sizes_from_registry()), but ttytype is a char array and thus constricts the maximum …
=> wingui: Fix for resize limits in registry overriding programmatically-set limits

.travis.yml, cmake/watcom_open_dos16_toolchain.cmake, cmake/watcom_open_dos32_toolchain.cmake, cmake/watcom_open_os2v2_toolchain.cmake
Travis has some asumption about compilers that safer is specify it explicitly for cross-compilation then use CMake detection. For CMake and Linux must be differ between names with and without file name extension.
=> Correct OW cross-compile stuff to work with Travis

.travis.yml
reorganize file to be more readable
use travis matrix dimensions environment variables to define all dependent variables to simplify travis jobs definition
setup TRAVIS_ARCH environment variable because Travis doesn't handle it correctly (new feature, not fully implemented)
use YML anchors and aliases to do file more readable
add DOSVGA wide version build
=> Reorganize .travis.yml file and add DOSVGA wide version build

.travis.yml, cmake/watcom_open_win32_toolchain.cmake
add CMake configuration file for Windows cross-compilation from Linux to Windows
use existing CMake Windows support file that only minimal definition is necessary
include win32 projects to build by travis
=> travis add WINCON and WINGUI project build for Open Watcom compilers

CMakeLists.txt
add it only for Windows target for now because it requires TCP/IP header files
for DOS some TCP/IP implementation must be selected
=> Add VT project build for Open Watcom cross-compilation

dos/CMakeLists.txt, dosvga/CMakeLists.txt, vt/CMakeLists.txt
only DOS 16-bit build uses large memory model
other targets are 32-bit and flat memory model
=> correct memory model setup for Open Watcom

wingui/pdcscrn.c
Currently, if a WinGUI program is started maximized (because it was last closed while maximized), the edges of the window (not covered by the Curses screen) will not be filled in. This patch fixes this by removing the `ValidateRect()` call in `set_up_window()`, which prevented any `WM_PAINT` messages from being sent at startup, and removing the window procedure's (redundant) check of `curscr` before calling `HandlePaint()`. (I also removed the `if` block altogether; when would the window procedure ever be called with a null `HWND`?)
Also, WinGUI currently uses `ExtractIcon()` to load the first icon (if present) in the application's executable. Ostensibly this function would be fine for the job, but it only seems to load a standard-size (e.g. 32 x 32) icon, potentially resulting in a …
=> wingui: Fix painting of edges when started maximized; improve icon loading

wingui/pdcdisp.c
Currently, a user is allowed to choose a proportional/non-monospace font, which will work but with messy results. Also, one can choose a script (character set). The `LOGFONT` structure returned by `PDC_get_logical_font()` always has the `lfCharSet` member set to `ANSI_CHARSET`, so selecting a different script with a font that's also `ANSI_CHARSET` compatible will have no effect, and a font that isn't compatible with `ANSI_CHARSET` (e.g. Terminal, and other "OEM/DOS" fonts) will fail to be used altogether when drawing the screen.
This patch adds `CF_FIXEDPITCHONLY` and `CF_SELECTSCRIPT` to the flags passed to `ChooseFont()` in `PDC_choose_a_new_font()`, so the font dialog will only list fixed-width/monospace fonts compatible with `ANSI_CHARSET`.
I also removed the assignment of the …
=> wingui: Restrict font dialog to compatible fonts

wingui/Makefile.mng
Commit b754e9862bc79720df6888b1fa955f9662d972dc missed updating WinGUI's MinGW/GCC makefile to use the libobjs.mif in the common directory. This pull request fixes this.
=> wingui: Fix MinGW makefile

wingui/pdcdisp.c, wingui/pdckbd.c, wingui/pdcscrn.c, wingui/pdcsetsc.c, wingui/pdcutil.c
Following up on issue #156, here's a proper way to fix the application hanging during a window resize or move.
I'm aware that WinGUI moved away from some sort of multi-threaded implementation several years back, but the synchronization code needed in this case is really pretty minimal and non-invasive. It uses a "critical section" object for synchronization. 
Before the window thread executes code that accesses or modifies sensitive shared variables, it requests ownership of the critical section object. The main thread owns the critical section except when it calls `PDC_napms()` or needs to make a Win32 API call that would *send* (as distinguished from "post") a message to the window and wait for it to be processed (the `SetWindowText()` call in `PDC_set_title()` is one instance, as is …
=> wingui: Move window procedure to separate thread to fix hanging/ugliness during resize/move

docs/HISTORY.md, sdl1/README.md, sdl1/pdcdisp.c, sdl1/pdcscrn.c, sdl1/pdcsdl.h, sdl2/README.md, sdl2/pdcdisp.c, sdl2/pdcscrn.c, sdl2/pdcsdl.h
The SDL2 version uses the 'Blended' version of the renderer, making it impossible to have pixel perfect fonts. I added a variable called `pdc_font_render_fast` which, if set, uses the 'solid' renderer, which is faster, but pixel accurate with no blending.
=> SDL-ports: Option to change font render from blended to shaded or solid

appveyor.yml, sdl2/sdltest.c
This is a follow up to #184. It fixes the issues for the Appveyor builds. It builds cleanly on Appveyor and Travis:
https://ci.appveyor.com/project/mannyamorim/pdcursesmod/builds/35602840
https://travis-ci.org/github/mannyamorim/PDCursesMod/builds/733436341
After #184 there were still 2 issue with Appveyor. The `winmm.lib` problem with Watcom and there was linker error with `sdltest.c` on MSVC. The root cause of the `winmm.lib` problem was that the `appveyor.yml` was missing the toolchain file for watcom_win32. This caused use to miss defining `WATCOM_WIN32` and caused the wrong libraries to be linked.
The linker issue with `sdltest.c` was caused by defining `pdc_sdl_render_mode` as an extern instead of using `PDCEX`. I fixed it by just removing the definitions and including the header …
=> Fix Appveyor Builds

wincon/Makefile
This PR solves https://github.com/Bill-Gray/PDCursesMod/issues/182
Per https://github.com/Bill-Gray/PDCursesMod/issues/176, -lwinmm was added to resolve an issue in `tuidemo`. On trying to build demos with `mingw32-make.exe -f Makefile demos`, I got the following error -
```
...
gcc -O4 -Wall -pedantic -I.. -ofirework.exe ../demos/firework.c pdcurses.a
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: pdcurses.a(pdcutil.o):pdcutil.c:(.text+0x13): undefined reference to `__imp_PlaySoundA'
...
``` 
Since the undefined reference comes from winmm.dll, setting EXELIBS to -lwinmm instead, makes sense. This change successfully compiled static library as well as demos
OS: Windows 10
Compiler: TDM-GCC-64
=> move -lwinmm flag from LIBSADDED to EXELIBS in wincon

sdl1/Makefile, sdl1/README.md, sdl2/Makefile, sdl2/README.md
* SDL1: `make libs` now makes pdcurses.so in addition to pdcurses.a.
* SDL2: You can build pdcurses.so/pdcurses.dylib with make `DLL=Y`. You can only build either pdcurses.a or pdcurses.so, consistent with the rest of the Makefile.
These changes are the same as those of the PR I made on PDCurses.
=> Implement SDL1 and SDL2 shared libraries

vt/pdcscrn.c
I have an application which does resizing like this:
```c
if (is_termresized()) resize_term(0, 0);
```
I had to make the change contained in this PR for the application to detect resizing using the vt backend. I don't know if the NULL check is necessary, but without it, it seems there could be a crash if the screen is resized right after `delscreen` is called.
This is mostly unrelated, but I think there is also unsafety in the signal handlers:
* `errno` should probably be saved and restored in the `SIGWINCH` handler in case `ioctl` fails.
* I don't know how to fix it, but the `SIGINT` handler calls `PDC_scr_close`, which calls `printf`. According to [this](https://man7.org/linux/man-pages/man7/signal-safety.7.html), `printf` is not safe inside signal handlers.
=> VT: Make SIGWINCH register with is_termresized

sdl2/pdcdisp.c
(This is the same change as in my PR for the original PDCurses. The following text is copied from that PR.)
I was having an issue when using Ubuntu MATE (but not GNOME Desktop): After a non-maximized window is minimized, it is not redrawn when it is restored. The window appears transparent until something causes it to redraw, e.g. the user resizing it. The change I have made fixes this.
I'm not exactly sure why this was an issue, but I think MATE might not be sending an `Expose` event, so this SDL code doesn't trigger: https://github.com/libsdl-org/SDL/blob/34ecd71e80b651c9840f60d91be60e30305fdc6f/src/video/x11/SDL_x11events.c#L1166. I was looking at where `SDL_WINDOWEVENT_SHOWN` is sent, and I think this is the place: https://github.com/libsdl-org/SDL/blob/34ecd71e80b651c9840f60d91be60e30 …
=> Fix SDL2 redrawing issue on Ubuntu MATE

sdl2/pdcscrn.c
I'm not sure when SDL2 started doing this, but I noticed the behavior with version 2.0.14. It seems like the palette size of a loaded bitmap surface is larger than the palette size of the actual bitmap. Therefore, the last color in the in-memory palette never actually shows up in the font. This leads to characters not being properly colored.
This patch adds some complex code because it needs to parse part of the bitmap file itself. A much simpler way to fix this issue would be to use the first and second palette entries rather than the first and last, but doing so might break user code.
Following is a modified version of the built-in font. It has 16 colors in its palette, although only 3 are used. Using it as the `PDC_FONT` with the `testcurs` program, you can see that the red in the A …
=> Fix non-wide sdl2 font coloration

x11/pdcscrn.c
These changes to the font width/height calculation make it match the calculation used by `XDrawImageString` more closely, although I haven't been able to find a whole lot of documentation on the subject. This PR is necessary to make some fonts such as `lucidasanstypewriter-*` work. Furthermore, according to my testing, this PR is necessary to make the default XCurses configuration work on Raspbian/LXDE. On this system, the default XCurses font is not available, so a fallback font is used (although I'm unsure what it is exactly.) Without this patch, the fallback font doesn't work.
Here are some pictures of the bug:
With the Raspbian/LXDE fallback font:
With `lucidasanstypewriter-10`:
For some reason, the width of a font character (`max_bounds.rbearing - min_bounds.lbearing`) is sometimes …
=> Improve x11 font compatibility

term.h
To allow using them also in shared object builds.
I haven't checked in detail but guess https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-pdcurses/002-fix-exports.patch does exactly the same thing.
Either we have them in for link compatibility, then they should be exported, or we don't.
Still feels "too intrusive" to just change, so PR @Bill-Gray .
=> export all our terminfo dummy functions

vt/pdcscrn.c
In VT port ^C and ^Z can now be treated as recognised keys
=> Enable ^C and ^Z to be recognised as keys

curses.h, wingui/pdcdisp.c, wingui/pdckbd.c, wingui/pdcscrn.c, wingui/pdcsetsc.c, wingui/pdcutil.c
Some time ago a change was merged into `PDCursesMod` to offload Window message handling to a background thread to make resizing happen more fluidly: https://github.com/Bill-Gray/PDCursesMod/commit/dd59e4cee70af08b86c111deba29cb7d2f795bb9
Unfortunately, this caused some issues with my apps. Specifically, I augment existing `PDCursesMod` functionality to do things like change the app icon and support minimizing to the notification tray. To do this, I get a reference to the main Window Handle (`HWND`), and call various Win32 API methods against it. Unfortunately, I am making these calls from the main app thread, not the thread running the message pump, so it leads to weird/undefined behavior that usually manifests as the app freezing at random times during operation, and very often during …
=> Fix resizing issues, remove multi-threaded message handling from `WinGUI` variant 

pdcurses/getstr.c
Casting an array of wchar_t to wint_t * works as intended only if wchar_t and wint_t have the same size. If they don't, wgetnstr will not work. Cast the elements to wchar_t instead.
=> Fix wgetnstr with PDC_WIDE

pdcurses/getch.c
... just a suggestion (and warning: I did not even tried to compile that...)
* early loop back if there is no key ready - at least during debugging this was quite often the case [which is the main reason for this suggestion]
* only check for copy/paste if we don't have a mouse event [occurred to me during adjustment when reading the code]
I was not 100% sure if the copy/paste keys may apply to the "filter special keys if not in keypad mode", if they aren't then this also does not need to be done when we have a mouse event and then also not in the copy paste code.
=> minor performance for getch

sdl1/pdckbd.c, sdl2/pdckbd.c
Wingui and X11 allow the user to call PDC_set_function_key() for FUNCTION_KEY_SHUT_DOWN so the user can handle the window close event within their program. This patch enables that capability for SDL1 and SDL2 ports
=> Enable user trapping of windows close on SDL1 and SDL2

pdcurses/util.c
There was a small typo in `PDC_mbtowc` with 4-byte UTF-8 code points, which caused characters past U+10000 to be converted incorrectly.
=> Fixed PDC_mbtowc with 4-byte code points

curses.h
This PR simply adds the `slk_attr()` to the exports in `curses.h`
Fixes #267
=> fix: added export slk_attr() to curses.h

.github/workflows/github_actions_build.yml
Tested and working in
https://github.com/rasa/PDCursesMod/actions/runs/4037625479/jobs/6941054143
via
https://github.com/rasa/PDCursesMod/blob/master/.github/workflows/windows-latest.yml
per
https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md#visual-studio-enterprise-2022
=> Switch to windows-2022 runner

docs/HISTORY.md, pdcurses/getch.c
With certain Unicode code points, the maximum length of a multi-byte string is 4 times the `wchar_t` string length, so let's multiply by 4 instead of 3. The way to trigger the bug was to:
1. Fill the screen with code points that expand to 4 bytes in UTF-8 (e.g. "🭂")
2. Attempt to repeatedly select large blocks of text (e.g. in the SDL2 port)
3. Observe as `double free or corruption (!prev)` happens!
=> Fix text selection memory corruption with long codepoints

demos/test_pan.c
Fixes error compiling using the more restrictive LLVM:
```bash
x86_64-w64-mingw32-gcc -Wall -Wextra -Werror -pedantic -fPIC -O2 -DPDC_WIDE -DPDC_FORCE_UTF8 -I..  -o test_pan.exe ../demos/test_pan.c libpdcurses.a -L/root/sdl2/SDL2-2.26.4/x86_64-w64-mingw32/lib -lmingw32 -lSDL2main -lSDL2 -mwindows -L/root/sdl2/SDL2_ttf-2.20.2/x86_64-w64-mingw32/lib -lSDL2_ttf
../demos/test_pan.c:72:9: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int main()
^
void
1 error generated.
make: *** [Makefile:203: test_pan.exe] Error 1
```
=> Fix: a function declaration without a prototype is deprecated in all versions of C

sdl2/Makefile, vt/Makefile, wincon/Makefile, wingui/Makefile
WINCON/WINGUI Makefile improvements/fixes:
- Added _a64 setting for cross-compilation for Windows on Arm.
- Enabled custom CFLAGS by adding flags instead of clearing the CFLAGS variable.
- Fixed missing prefixes to complete the AR and STRIP commands to properly support cross-compiling.
=> [WINCON/WINGUI/SDL2/VT] Added support for cross compilation for Windows on Arm: Enabled custom CFLAGS. Fix missing prefixes for AR and STRIP

wingui/pdcdisp.c, wingui/pdcscrn.c
Use `STDAPICALLTYPE` when dynamically resolving DPI-related API calls.
=> Fix calling convention for Win32 DPI-related API calls.

curses.h
always use modifier `extern`, not only the attribute `__declspec`
Note: this works "as-is" since >17 years, but I still think the attribute should not be used "alone"
=> [WIN32] external definition adjusted

gl/pdckbd.c, sdl2/pdckbd.c
SDL_PollEvent was always returning 0, which meant we never set `action = BUTTON_CLICKED`. Using SDL_WaitEventTimeout instead of napms followed by SDL_PollEvent seems to fix this.
I mentioned this bug in issue #117.
=> Fixed issue where mouse clicks were always reported as separate button down and button up events.

gl/pdckbd.c, sdl2/pdckbd.c
SDL2 and GL builds were not detecting double or triple clicks, but instead would just produce a series of single click events when clicking multiple times. This simply turns the click detection into a loop that increments from BUTTON_PRESSED to BUTTON_CLICKED to BUTTON_DOUBLE_CLICKED to BUTTON_TRIPLE_CLICKED and bails out if any other input is received.
I get the impression from #117 that you wanted to refine the logic for double and triple click detection used in wingui and then port it over to other platforms, but maybe we can use this for sdl2 and gl until then.
=> Added double and triple click detection for SDL2 and GL

common/winclip.c
As with other clipboard command, the clipboard needs to be open for them to work.
=> Clear clipboard requires clipboard to be opened
